spring:
  config:
    activate:
      on-profile: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_project
    username: root
    password: 1q2w3e4r!